version: 0.2

env:
  variables:
    ECR_REPO_NAME: test/ecs-sqs-producer

phases:
  pre_build:
    commands:
      - set -x
      - echo "test start"

  build:
    commands:
      - test -f imagedefinitions.json
      - cat imagedefinitions.json
      - grep '"name":"app"' imagedefinitions.json
      - grep '"imageUri":"' imagedefinitions.json
      - grep 'test/ecs-sqs-producer:latest' imagedefinitions.json
      - echo "imageUri check passed"

  post_build:
    commands:
      - echo "test passed"

artifacts:
  files:
    - imagedefinitions.json
