version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-1
    LAMBDA_FUNCTION_NAME: test
    LAMBDA_ALIAS_NAME: prod

phases:
  build:
    commands:
      - echo "== build zip =="
      - cd "$CODEBUILD_SRC_DIR/lambda"
      - cd src
      - zip -r ../lambda.zip .
      - cd ..
      - echo "ZIP created:"
      - ls -lh lambda.zip

  post_build:
    commands:
      - echo "== update lambda code + publish version =="
      - cd "$CODEBUILD_SRC_DIR/lambda"
      - CURRENT_VERSION=$(aws lambda get-alias --function-name "${LAMBDA_FUNCTION_NAME}" --name "${LAMBDA_ALIAS_NAME}" --region "${AWS_REGION}" --query 'FunctionVersion' --output text)
      - echo "CURRENT_VERSION=${CURRENT_VERSION}"
      - aws lambda update-function-code --function-name "${LAMBDA_FUNCTION_NAME}" --zip-file "fileb://lambda.zip" --region "${AWS_REGION}"
      - TARGET_VERSION=$(aws lambda publish-version --function-name "${LAMBDA_FUNCTION_NAME}" --region "${AWS_REGION}" --query 'Version' --output text)
      - echo "TARGET_VERSION=${TARGET_VERSION}"

      - |
        cat > appspec.yml <<EOF
        version: 0.0
        Resources:
          - MyLambdaFunction:
              Type: AWS::Lambda::Function
              Properties:
                Name: ${LAMBDA_FUNCTION_NAME}
                Alias: ${LAMBDA_ALIAS_NAME}
                CurrentVersion: "${CURRENT_VERSION}"
                TargetVersion: "${TARGET_VERSION}"
        EOF

      - echo "== generated appspec.yml =="
      - cat appspec.yml

artifacts:
  files:
    - lambda/appspec.yml
